### ISSUE TITLE
Время жизни объекта

### ISSUE THREAD

**Issue by alexmikhalevich** [regu1yar/Pizzeria#1]
Интересный подход. Т.е. я не могу сделать так:
```
...
Pizza* pizza_ptr = nullptr;
{
    PizzaBuilder builder;
    //building pizza ...
    pizza_ptr = builder.getPizza();
}
// some operations with pizza_ptr
...
```
Кажется, что это стандартный кейс, не согласен?

https://github.com/regu1yar/Pizzeria/blob/bd4a8646745cc6a8fcc446cd14c8b2b59047b208/Pizza.h#L34

**Comment by regu1yar** [comment]
Реализовал создание пиццы через shared_ptr. Подобный сценарий протестирован в файле PtrTest.h.
